### ISSUE TITLE
Angel ring recipe not showing in NEI after 1.1

### ISSUE THREAD

**Issue by Saereth** [nutsandboltspack/nutsandbolts#18]
The recipe doesn't show, didnt try crafting one with the old recipe but I'm guessing it's broken.

**Comment by Milkyway3640** [comment]
Angel ring crafting was disabled...

...yay...

**Comment by 666lumberjack** [comment]
the script is broken, I'm working on it

**Comment by Saereth** [comment]
The ring and recipe now shows in NEI but is still not craftable. shift+clicking into a crafting grid doesnt recognize the diamond blocks as part of the recipe and manually inserting all the components doesnt work.

**Comment by downslope7** [comment]
Fixed minetweaker scripts and changed recipe to use regular vanilla diamond blocks.
