### ISSUE TITLE
New mods to add in 1.2.0

### ISSUE THREAD

**Issue by 666lumberjack** [nutsandboltspack/nutsandbolts#19]
Aura Cascade
Warp Theory 
OpenPeripheral

suggestions?

**Comment by Saereth** [comment]
Ok some ideas...

magic crops, heaivly nerfed for the decorative blocks+fun 
im thinking reduced drops per seed, no extra seeds, no essence seeds

Also
Quarry+ has been updated to 1.7.10 and the developer is working on it again, looks good and eliminates the problems of a bc quarry with the ability to use pump+ with it.

**Comment by 666lumberjack** [comment]
Magical Crops: Unbalancably powerful until he adds a chance of dropping 0 seeds, which I believe is coming. If/when that happen's I'll reconsider. 

Quarry+
Maybe. That's all I'll say for now.

**Comment by Saereth** [comment]
Also kinkodoyle suggested and I agree, openPeripherals would be very nice and open up some neat builds

**Comment by downslope7** [comment]
Holding off on these.

&nbsp;

&nbsp;


&nbsp;


&nbsp;

<sup>Except OpenPeripherals which I just snuck in to v1.2.3 and released.</sup>
