### ISSUE TITLE
Serious issue, Inventory deleted on death.

### ISSUE THREAD

**Issue by Saereth** [nutsandboltspack/nutsandbolts#20]
Died around 12:18AM ESt at my house just testing armors, immediately crashed with this crash log:

http://pastebin.com/iHJMdRpg

Looks like the malaises door again

After logging back in I broke my gravestone and the only thing in there was the cosmetic armor and of course the galacticraft stuff floating nearby which has never gone in the grave.

**Comment by Saereth** [comment]
Rebuilt my jetplate and some other stuff, died while afk to warp effect and the same thing happened again. So I did some testing just took a few things in my inventory, no Galacticraft or cosmetic armors and died, no gravestone at all appeared when I only had some food items in my inventory. Seems like your inventory/equipped items are just completely deleted on death atm.

**Comment by 666lumberjack** [comment]
Could you try removing Erebus completely and testing in singleplayer?

**Comment by downslope7** [comment]
Disabled erebus and openblocks graves entirely for now, too many issues.
