### ISSUE TITLE
Minetweaker Recipes Broken

### ISSUE THREAD

**Issue by aRedPenguin** [nutsandboltspack/nutsandbolts#21]
All items that previously had tweaked recipes now have no recipe.

I suspect this is because there is a script for Practicalities and since that mod was removed it is erroring out

**Comment by 666lumberjack** [comment]
Yup, that's probably it. I completely forgot that we tweaked practicalities in the end. Will remove the offending stuff and have DS update.

**Comment by downslope7** [comment]
Fixed during v1.1's tenure server-side and in the scripts distrubuted with v1.2.0.
