### ISSUE TITLE
Suggestion: Alternate Green heart recipe

### ISSUE THREAD

**Issue by Saereth** [nutsandboltspack/nutsandbolts#23]
An alternate green heart recipe involving one of the exploration areas or a tech path would be nice so people still have the freedom of choice in their progression. The tool forge is a good example, you can do blood magic but there is also the atum option. I think that's better approach than locking TiC hearts behind BM soley.

**Comment by downslope7** [comment]
Any ideas? Going to do a rehaul of the minetweaker scripts in the next few days.

**Comment by Saereth** [comment]
I think a ludacrite ingot + yellow heart would be about the equivalent to the current BM recipe

**Comment by Saereth** [comment]
New recipes were added
