### ISSUE TITLE
Yellorium Blocks uncraftable

### ISSUE THREAD

**Issue by Saereth** [nutsandboltspack/nutsandbolts#27]
trying to turn 9 yellorium ingots and blocks results in venus uranium blocks. Although venus uranium ingots work as BR fuel, the uranium blocks do not. Uranium blocks need to be added as valid BR fuel or recipe corrected. Oddly enough someone with w/w/w enderchest had about 10 stacks of 64 blocks of yellorite floating around and I cant for the life of me figure out how they managed to craft them...

**Comment by downslope7** [comment]
Caused by the same issue as #4 - fixed a while ago.
