### ISSUE TITLE
Redstone signals are semi broken

### ISSUE THREAD

**Issue by Saereth** [nutsandboltspack/nutsandbolts#28]
Signals projected from a source do not activate the block directly adjacent to them.

For example. Place a redstone lamp, now place a redstone torch directly next to it, it wont work!
now move the torch another block away and it will work. This bug applies to AE level emitters and I'd imagine several other sources as well. Slope is aware/helped test just filling a report here to help track.

**Comment by downslope7** [comment]
Fixed by removing RemoteIO, at least temporarily.
