### ISSUE TITLE
Sigil of Destruction: Tier 3 recipe incorrect

### ISSUE THREAD

**Issue by PyrotekNick** [nutsandboltspack/nutsandbolts#30]
The Tier 1 and Tier 2 require a shovel, pickaxe, and axe across the top row (left to right). The Tier 3 recipe (from the NEI) shows two shovels and an axe. When I attempted to use the 2 shovels and the axe, no crafting occurs.

**Comment by downslope7** [comment]
All custom recipes have been redone.
