### ISSUE TITLE
Mod Updates Missed in 1.1 Updated

### ISSUE THREAD

**Issue by Milkyway3640** [nutsandboltspack/nutsandbolts#31]
Buildcraft
http://www.mod-buildcraft.com/download/

Thaumcraft
http://www.curse.com/mc-mods/minecraft/223628-thaumcraft#t1:other-downloads

Forbidden Magic
http://minecraft.curseforge.com/mc-mods/224237-forbidden-magic/files

Biomes O' Plenty (Maybe we shouldn't touch this one...)
http://files.minecraftforge.net/BiomesOPlenty/

Extra Cells
http://shadowcity.net:8080/job/ecrv2/lastSuccessfulBuild/

Tinkerer's Construct
http://www.curse.com/mc-mods/minecraft/tinkers-construct#t1:other-downloads

Electrical Age
https://github.com/Dolu1990/ElectricalAge/releases/tag/BETA-1.9

Buildcraft Additions
http://minecraft.curseforge.com/mc-mods/221014-buildcraft-additions/files/2225232

Eternal Frost (ew)
http://www.mediafire.com/download/wwq2d648jbxaxf9/eternalfrost-2.0b5.jar

Botania
http://vazkii.us/mod/Botania/downloads.php

Compact Machines
http://minecraft.curseforge.com/mc-mods/224218-compact-machines/files

Dragon API
https://sites.google.com/site/reikasminecraft/latest-downloads

Expanded Redstone
https://sites.google.com/site/reikasminecraft/latest-downloads

Ender IO
http://minecraft.curseforge.com/mc-mods/64578-ender-io/files

Malisis's Core 
http://minecraft.curseforge.com/mc-mods/223896-malisiscore/files

Malisis's Doors
http://minecraft.curseforge.com/mc-mods/223891-malisis-doors/files

NEI Addons
http://jenkins.bdew.net/job/neiaddons-1.7.10/

NEI Integration
http://minecraft.curseforge.com/mc-mods/225251-nei-integration/files

RotaryCraft
https://sites.google.com/site/reikasminecraft/latest-downloads

TiC Tool Tips
http://minecraft.curseforge.com/mc-mods/76845-tic-tooltips/files

Waila
http://www.curse.com/mc-mods/minecraft/waila#t1:other-downloads

Thaumic Energistics
http://minecraft.curseforge.com/mc-mods/223666-thaumic-energistics/files

Random Things
http://www.curse.com/mc-mods/minecraft/random-things#t1:other-downloads

Logistics Pipes
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1289546-buildcraft-logistics-pipes#downloads

Thaumic Exploration
http://jenkins.nekokittygames.com:8080/view/Thaumic%20Explorer/job/Thaumic%20Explorer/

Binnies Mods
http://minecraft.curseforge.com/mc-mods/223525-binnies-mods/files

Chisel 2
http://www.curse.com/mc-mods/minecraft/225236-chisel-2#t1:other-downloads

Greg's Lighting/ Flood Lights  http://www.cosc.canterbury.ac.nz/greg.ewing/minecraft/mods/GregsLighting/#mozTocId552632

Funky Locomotion
http://minecraft.curseforge.com/mc-mods/224190-funky-locomotion/files

Micdoodle8 Core + Galacticraft + Galacticraft Planets
http://micdoodle8.com/mods/galacticraft/downloads

Advanced Generators
http://jenkins.bdew.net/job/generators-1.7.10/lastBuild/

Hard Core Ender Expansion
http://www.mediafire.com/download/5lr1z55flk0935p/HEE_1.7.10_release-1.7.zip

MFFS
http://calclavia.com/mffs/downloads/

Applied Energistics
http://ae-mod.info/Downloads/

Project Red - Maybe Beta
http://projectredwiki.com/wiki/Version_archive

Thaumic Energistics
http://minecraft.curseforge.com/mc-mods/223666-thaumic-energistics/files/2224421

Tinkerer's Mechworks
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1446244-1-6-4-tinkers-mechworks

**Comment by downslope7** [comment]
Went through everything and updated. Released as v1.2.0.

The following were not able to be added, though. We'll need to revisit in a few days/weeks.

* **Buildcraft** - Drops the MJ API; this breaks compatibility with DragonAPI at the very least. Milky has a dropbox link to a DragonAPI without MJ api use, will investigate.
* **Waila** - newest Waila is experimental and depends on newest NEI / CodeChickenCore. Other mods don't like these yet.
* **MFFS** - new version asplodes on launch. Need to investigate.
* **Advanced Generators** - Go boom on launch, maybe BC API related. Need more data. 
* **Applied Energistics** - causes DragonAPI to barf, need to do a bit more research.
