### ISSUE TITLE
Thaumcraft champion drops too strong

### ISSUE THREAD

**Issue by Saereth** [nutsandboltspack/nutsandbolts#32]
The treasure bags from Thaumcraft champion mobs are really overpowered atm. A single night running a cursed earth spawner yielded 400 emeralds, 700 diamonds, 3 nether stars, 1500 gold bars and tons of other stuff at basically no cost to operate. This is attainable early in the game and easy to automate.

**Comment by downslope7** [comment]
This should have been improved significantly in v1.2.5; they were pretty heavily nerfed by the man himself.
