### ISSUE TITLE
Talisman of Nourishment Bugged

### ISSUE THREAD

**Issue by DarkLordIce** [nutsandboltspack/nutsandbolts#34]
If talisman+a food item for it to consume are on your hotbar, an instant disconnect with the error message "Internal Server Error" happens.  Does not seem to affect the server, just player disconnect.

Was able to resolve by spaming drop item as I logged back in to prevent the attempted consumption

**Comment by downslope7** [comment]
Issue is listed here nekosune/Thaumic_Exploration#21- the Talisman of Nourishment wasn't tested in SMP, just SSP.
