### ISSUE TITLE
Mod suggestion

### ISSUE THREAD

**Issue by stickhead** [nutsandboltspack/nutsandbolts#36]
Since everybody has been spamming cursed earth in an attempt to make mob spawners, which has completely destroyed FPS in the nether, I propose we add soul shards. 
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/1445947-1-7-10-soul-shards-reborn-original-soul-shards
I'm quite familiar with the mod, and you can essentially make your own spawners (not cheap) for any non boss mob.

**Comment by Saereth** [comment]
There are already a couple ways to do this with this pack, cursed earth is just a super east/cheap way of creating mass mobs for farming/sacrificing etc so it becomes the goto method. even with soul shards I'm willing to bet there would still be large cursed earth farms on the server. And in reality they arent that bad themselves but when people leave them unattended with no automated killing it causes real problems.

**Comment by stickhead** [comment]
Was just saying, with Soul Shards it would be easier to farm Wither Skeles, and in turn easier to get skulls.

**Comment by downslope7** [comment]
A skeleton wrath cage in the nether will spawn wither skeletons too. I'm going to say no for now, we already have quite a bit of bloat in the pack and there is too much overlap.
