### ISSUE TITLE
Extending endgame with ReactorCraft

### ISSUE THREAD

**Issue by Saereth** [nutsandboltspack/nutsandbolts#37]
Would love to see ReactorCraft added to the game, it greatly extends endgame opportunities. I think of it as fulfilling the role of gregtech for keeping long term options for the players. Most of the framework for it already exists with rotarycraft and the APIs associated with that. The only problem is it requires some custom ores so we'd be looking at a map reset or at least some retrogen. Well worth it though imo.

**Comment by downslope7** [comment]
Added in v1.3
