### ISSUE TITLE
NEI not displaying Enderquarry upgrade correctly

### ISSUE THREAD

**Issue by Saereth** [nutsandboltspack/nutsandbolts#4]
The tier 2 and 3 enderquarry speed upgrade recipes do not show correctly in NEI but are craftable with the recipe. Pretty sure you guys are aware just documenting!

**Comment by downslope7** [comment]
This was caused when we removed Practicalities. It made a MT recipe modification invalid; every recipe in that script below that line was summarily ignored. Fixed quite a while ago.
