### ISSUE TITLE
Crash on world start

### ISSUE THREAD

**Issue by mamgar** [nutsandboltspack/nutsandbolts#51]
http://pastebin.com/BK43HHZm made it about 6 minutes into a new world but game freezes and crashes as soon as i load it up.

**Comment by mamgar** [comment]
removing custom npc's seemed to stop the game from crashing

**Comment by downslope7** [comment]
That's interesting, the error that you are seeing looks like an entity id conflict. I checked everything manually when we assigned everything ids but the problem is some mods use ids without registering them correctly with forge (I think, at least...)

I'll check again when I have a moment.

**Comment by downslope7** [comment]
I changed the CustomNPCs entity IDs to ones that I knew were completely free. Seems to have fixed the issue for me, can you verify?
