### ISSUE TITLE
Silent crash on launch

### ISSUE THREAD

**Issue by NeoPariah** [nutsandboltspack/nutsandbolts#52]
When I attempt to launch Nuts and Bolts from the Technic Launcher, the app crashes silently (doesn't display any errors). This issue occurs on both my home and work machines, both of which are running OS X 10.10.2. I've also encountered a very similar issue in Windows 8.1 at home. Since starting to try a month ago, I've never successfully launched N&B. I've tried:
-deleting ~/Library/Application Support/technic/
-redownloading the Technic Launcher
-reinstalling Java for OS X 2014-001 and Java 8
-testing for the issue in a newly created user (occurs there, too)
-reinstalling OS X
-using both the default settings, and upping the RAM to 4GB plus adding "-XX:PermSize=256M" to the Java arguments

To provide a clean log, I just redownloaded the Technic Launcher, deleted ~/Library/Application Support/technic/, installed Nuts and Bolts, upped the RAM to 4GB, added "-XX:PermSize=256M" to the Java arguments, and attempted to launch it once. I then copy and pasted the technic console log to http://pastebin.com/FuiNMXam . I'm happy to try any further troubleshooting you'd like me to.

**Comment by downslope7** [comment]
Your computer is using Java 6 as a default instead of the one that you installed. See line 1129 which begins with this:

```[B#283] Running /System/Library/Java/JavaVirtualMachines/1.6.0.jdk/Contents/Home/bin/java -Xdock:name=Nuts & Bolts -Xmx4096m -XX:MaxPermSize=256m -Djava.library.path=/Users/gpage/Library/Application Support/technic/modpacks/nuts-and-bolts-alpha/bin/natives -Dfml.core.libraries.mirror=http://mirror.technicpack.net/Technic/lib/fml/%s -```

You should be able to check your java version in the new Technic Launcher. Click Launcher Options -> Java Settings -> Minecraft Java Version. It should look something like this: 

![settings](http://i.imgur.com/gnpJusJ.png).

**Comment by NeoPariah** [comment]
That was the root of the issue. Neither copy of the Technic Launcher was
detecting Java 8, and it's impossible to select the correct file manually
with the JRE. (It's buried in a package. The manual selection dialog isn't
a native open dialog, so I can't open package contents. Installing the JDK
let the launcher see Java 8.
