### ISSUE TITLE
I found me a bug, and its a big ol' feller. 

### ISSUE THREAD

**Issue by Delaura** [nutsandboltspack/nutsandbolts#55]
Redstone Arsenal Pickaxe on Powered Mode = Server Shutdown. Tested it 2 times early this morning at around 2am EST.

There is no doubt my actions (breaking one cobblestone block (I should note it was a chisel 2 block in case that means anything)) did crash the server. I have since stored away the pickaxe and become infatuated with the idea of being this server's harbinger of death.  

Bow down before me.

Eh Im bored already.  Anyway. I have not tried any other redstone arsenal tools because its freaking expensive and i dont wanna waste more diamonds.   

~Aetryx

**Comment by downslope7** [comment]
Fixed with latest update of CoFH stuff.
