### ISSUE TITLE
Issue logging in with the latest update.

### ISSUE THREAD

**Issue by Steepfence** [nutsandboltspack/nutsandbolts#60]

**Comment by downslope7** [comment]
What happens exactly?

**Comment by Steepfence** [comment]
Gives me an error with : The following microblocks are not installed on this client: tile.whiteStone

**Comment by downslope7** [comment]
Try to do a pack reset and make sure you're on the newest recommended.

**Comment by Steepfence** [comment]
I did and I am

**Comment by downslope7** [comment]
Other people are experiencing this in other packs, too, starting today. Investigating...

**Comment by Steepfence** [comment]
Sherlock Downslope is on the case. Thanks man

**Comment by capSAR273** [comment]
Just chiming in to say I experience the same error, whether connecting via direct connect, manually, or the "Join Server" button at the main menu :) Newest version also.

**Comment by downslope7** [comment]
It's an issue caused by an April Fools joke :) 

Open `HardcoreEnderExpansion.cfg`  and change `hardcoreEnderbacon` to 2. That should fix it.
